version: '3.8'

services:
  app:
    image: nodejs-express-mongodb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_CONNECTIONSTRING=mongodb://mongo:27017/your-database-name
      - REDIS_HOST=redis
      - PORT=8080
      - SECRET_KEY=your-secret-key
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data: